source 'git@code.inke.cn:nvwa/client/Santorini/Specs.git'
source 'git@code.inke.cn:tpc/client/platform/ios/PlatformSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!
install! 'cocoapods',
      :generate_multiple_pod_projects => true,
      :incremental_installation => true

def inke
  # 基础库统一指向git@code.inke.cn:tpc/client/platform/ios
  # 如果编译失败，首先考虑指定最新的tag
  pod 'IKLog', '~> 1.0.3'
  pod 'IKFoundation', '~> 1.0.8'
  pod 'IKModuleCenter', '~> 1.1.4'
  pod 'IKAppAtom/Core', '~> 1.2.1'
  pod 'IKPersistentConnectionAdapter', '~> 0.2.2'
  pod 'IKVideoSDK', '8.0.40.12-nvwa'
  pod 'IKCrypt'
  pod 'IKPersistentConnection', '~> 0.2.3'
  pod 'IKNetwork', '~> 1.3.2'
  pod 'IKDataAnalytics', '~> 1.0.2'
  pod 'RSSwizzle', '~> 0.1.1'

  pod 'IKAOPDataAnalytics', '~> 0.1.0'
  pod 'IKAppAtom/ShuMei', '~> 1.2.1'
  pod 'IKShuMeiSDK', '~> 2.6.4.1'
  pod 'IKRouter', '~> 2.0.0'
  pod 'IKPush', :git => 'git@code.inke.cn:tpc/client/platform/ios/IKPush.git', :tag => '1.0.2'
  pod 'SDVersion', :git => 'git@code.inke.cn:tpc/client/ios/inke/IKSDVersion.git', :branch => 'master'
end




target 'Eos' do
  nvwa
  inke
  openSources
  eos
end

